/* Autogenerated by png2wx.pl on Sat Feb  3 13:26:08 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_AutoTrackRaymarine;

#ifdef PLUGIN_USE_SVG
   extern wxString _svg_tracking;
   extern wxString _svg_tracking_rollover;
   extern wxString _svg_tracking_toggled;
#endif

#endif /* ICONS_H */
