/* Autogenerated by png2wx.pl on Sat Feb  3 13:26:08 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_AutoTrackRaymarine;

#endif /* ICONS_H */
